site_name: ELA PORTAL
site_url: https://sotarotakano.github.io/ela-home-docs/
theme:
    name: readthedocs
    custom_dir: custom_theme
nav:
    - Home: index.md
    - Cited by: citations.md
extra:
  analytics:
    provider: google
    property: G-WRRLXDCD9W